ARG DEBIAN_FRONTEND=noninteractive # avoid tzdata asking for configuration
# Install needed tools
RUN apt-get -y update && apt-get install -y \
  python \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
