ARG DEBIAN_FRONTEND=noninteractive # avoid tzdata asking for configuration
# Install needed tools
RUN apt-get -y update && apt-get install -y \
  apt-utils \
  pkg-config \
  autotools-dev \
  automake \
  libtool \
  autoconf-archive \
  autopoint \
  m4 \
  flex \
  libcap-dev \
  libssl-dev \
  zlib1g-dev \
  byacc \
  bison \
  autoconf \
  freeglut3-dev \
  unzip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN locale-gen "en_US.UTF-8"