ARG DEBIAN_FRONTEND=noninteractive # avoid tzdata asking for configuration
# Install needed tools
RUN apt-get -y update && apt-get install -y \
  locales \
  curl \
  ca-certificates \
  build-essential \
  autotools-dev \
  autoconf \
  m4 \
  libtool \
  openssh-server \
  git \
  gcovr \
  sudo \
  iptables \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN locale-gen "en_US.UTF-8"