
if(DEFINED POLLY_FLAGS_CXX17_CMAKE)
  return()
else()
  set(POLLY_FLAGS_CXX17_CMAKE 1)
endif()

set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ Standard (toolchain)" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED YES CACHE BOOL "C++ Standard required" FORCE)
set(CMAKE_CXX_EXTENSIONS NO CACHE BOOL "C++ Standard extensions" FORCE)
