name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

env: 
  TIPI_CACHE_FORCE_ENABLE: ON
  TIPI_ACCESS_TOKEN: "${{ secrets.TIPI_ACCESS_TOKEN }}"
  TIPI_REFRESH_TOKEN: "${{ secrets.TIPI_REFRESH_TOKEN }}"
  TIPI_VAULT_PASSPHRASE: ${{ secrets.TIPI_VAULT_PASSPHRASE }}

jobs:
  build: 
    name: build-host-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cmake-re --host builds project within tipi-container
        run: |
          cmake-re --host -S . -B ./build-host -DCMAKE_TOOLCHAIN_FILE=environments/linux.cmake
          cmake-re --build ./build-host